[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
[theme]
base="dark"
primaryColor="#1DB954"       # green highlight (you can change)
backgroundColor="#0e1117"    # app background
secondaryBackgroundColor="#161b22"  # cards / sidebar background
textColor="#fafafa"          # text
font="sans serif"
